### ISSUE TITLE
sub field is the django user ID by default

### ISSUE THREAD

**Issue by uwekamper** [c-base/c-base-oauth2#1]
![image](https://user-images.githubusercontent.com/8845940/142512176-24bfc20f-cf67-42dd-9b5f-caafe8e9aaf0.png)

`"sub": 18` should be `"sub": "{c-base username}"` or the c-base uid from LDAP `"sub": 3123`

**Comment by ForsakenHarmony** [comment]
For reference: https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims
`sub` could be either the c-base member name or member id
`email` is self-explanatory
maybe `preferred_username` as member name if full name is something we want to return in `name` (LDAP does not have everyone's full name anyway)

**Comment by uwekamper** [comment]
fixed.
